# Generated by Django 5.0.3 on 2025-10-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_datainformation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainformation',
            name='content',
            field=models.TextField(),
        ),
    ]
